import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "New Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const link = [
    {link:"/",name:"Home"},
    {link:"/about",name:"About"},
    {link:"/",name:"Transaction"},
    {link:"/",name:"Jobs"},
    {link:"/",name:"Contect"}
  ];
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
       
      </body>
    </html>
    </ClerkProvider>
  );
}
